### ISSUE TITLE
macOS Mojave 10.14 Support?

### ISSUE THREAD

**Issue by feisar-uk** [ruggi/walvis#1]
This looks great, but unfortunately I'm stuck on Mojave for now. Any chance of a version that runs on earlier than Catalina OSs? Thanks.

**Comment by ruggi** [comment]
Glad you like it! I'll look into supporting previous macOS versions, it should not be a problem :)

**Comment by ruggi** [comment]
@feisar-uk could you try and see if https://github.com/ruggi/whale/releases/tag/1.5.0 works fine for you now?

**Comment by feisar-uk** [comment]
Just tried it and unfortunately, it still say's it requires macOS 10.15 or later:

![2020-07-01 at 11 57](https://user-images.githubusercontent.com/8984413/86236568-3494ae80-bb92-11ea-83ac-25c8cee30b4d.png)

**Comment by ruggi** [comment]
mmh, I see, let me dig a little more

**Comment by feisar-uk** [comment]
If there's anything I can do to assist, just let me know. Thanks.

**Comment by feisar-uk** [comment]
Running `/Applications/Whale.app/Contents/MacOS/whale` from the Terminal gives the following error output:

```
 dyld: lazy symbol binding failed: Symbol not found: _objc_opt_new
  Referenced from: /Applications/Whale.app/Contents/MacOS/whale (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib

dyld: Symbol not found: _objc_opt_new
  Referenced from: /Applications/Whale.app/Contents/MacOS/whale (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib

SIGABRT: abort
```

Does that give any clues?

**Comment by ruggi** [comment]
https://github.com/ruggi/whale/releases/tag/1.5.1 ?

**Comment by feisar-uk** [comment]
Yes! That runs, and a quick test seems to show it works as expected. Will continue to do more in-depth testing.

Thank you, that's really great.

**Comment by ruggi** [comment]
thanks! all feedback is appreciated :)
