### ISSUE TITLE
Show http port in menu and open in browser

### ISSUE THREAD

**Issue by feisar-uk** [ruggi/walvis#2]
It's working great in Mojave 🙏, so here's my first bit of feedback.

For containers that make http port 80 available (such as Apache, WordPress, phpMyAdmin) could you show the port it is mapped to in the menu, and provide a sub-menu item to open that port in the default browser?

For example:

![web-port](https://user-images.githubusercontent.com/8984413/86243118-b3431900-bb9d-11ea-8ffc-db2b83abed8d.png)

I use Docker primarily for offline web development and being able to quickly open web accessible containers in the browser would be a real time-saver.

**Comment by ruggi** [comment]
that sounds like a good improvement, thanks for the suggestion 👍 
it should be pretty straightforward, I'll keep you posted ;)

**Comment by ruggi** [comment]
@feisar-uk what about something like this?

![Kapture 2020-07-01 at 16 27 29](https://user-images.githubusercontent.com/1081051/86255842-eb575580-bbb7-11ea-8482-117045c13b36.gif)

It should accommodate nicely for both services with just a single port binding as well as multiple ones. It will open the links with the system's default browser (please don't mind the random ports for the services in the GIF, I just threw a simple docker-compose together for testing the outputs).

**Comment by feisar-uk** [comment]
Wow, that was quick! Yes, that looks perfect.

**Comment by ruggi** [comment]
✅ https://github.com/ruggi/whale/releases/tag/1.6.0 :)
