### ISSUE TITLE
Issues with Open in browser menu item

### ISSUE THREAD

**Issue by feisar-uk** [ruggi/walvis#4]
Something may have changed in Docker recently to cause this as it used to work perfectly.

However, now, the Open in browser menu item lists the port twice:

![2021-06-05 at 20 23](https://user-images.githubusercontent.com/8984413/120903080-fc1c1100-c63b-11eb-9272-0637cc153f86.png)

...and when you select either one of these port options, it adds two extra colons into the URL it attempts to open. For example, instead of attempting to open ``http://localhost:8091`` it tries to open ``http://localhost:::8091``

Thanks.

**Comment by ruggi** [comment]
Thanks for the issue, will look into it :)

**Comment by ruggi** [comment]
Fixed in https://github.com/ruggi/whale/releases/tag/1.7.0
