### ISSUE TITLE
Universal build for Apple Silicon

### ISSUE THREAD

**Issue by feisar-uk** [ruggi/walvis#7]
Any chance of a universal build to include Apple Silicon M1 and M2 chips?

Thanks.

**Comment by julian-tr** [comment]
+1 for an Apple Silicon build. Whale is so much better than the Electron-based alternatives out there.

If you don't have time for this yourself, would you consider publishing the source code?

**Comment by ruggi** [comment]
Added in https://github.com/ruggi/whale/releases/tag/1.8.0 , and I'm cleaning up the source code to publish this as OSS :)
